language: python
python:
  - "2.7"
cache: pip
# command to install dependencies
install:  
  - pip install -r ProdirectScraper/requirements.txt
  - pip install coveralls
  - pip install  coverage
# command to run tests
before_script: cd ProdirectScraper
script:
  - coverage run -m -p unittest tests.test_helpers
  - coverage run -m -p unittest tests.test_page_spider
  - coverage combine
  - coverage report -m
after_success:
  - coveralls
